version: '3.9'
services:
  db:
    image: postgres:15.0-alpine
    restart: always
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=hypertube
    ports:
    - '5434:5432'
  testdb:
    image: postgres:15.0-alpine
    restart: always
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=hypertube-test
    ports:
    - '5435:5432'